version: '3.7'
services:
    app:
        build: ./bankless-backend-app
        restart: on-failure
        env_file: ./bankless-backend-app/.env
        environment:
            WAIT_HOSTS: mongodb:27017, redis:6379
        networks:
            - default
            - bankless-backend-network
        ports:
            - '4000:4000/tcp'
        links:
            - mongodb
            - redis
        depends_on:
            - mongodb
            - redis
    mongodb:
        image: mongo:latest
        restart: on-failure
        environment:
            MONGO_INITDB_ROOT_USERNAME: banklessbackend
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - persist:/data/db
        networks:
            - bankless-backend-network
        ports:
            - '27017:27017/tcp'
    redis:
        image: redis:latest
        restart: on-failure
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data
        networks:
            - bankless-backend-network
        ports:
            - '6379:6379/tcp'
    frontend:
        build: ./bankless-frontend
        restart: on-failure
        networks:
            - default
        ports:
            - '80:4173/tcp'
        healthcheck:
          #test: ["CMD", "curl", "-f", "http://localhost:4173"]
          test:
           - CMD-SHELL
           - '[ "$(curl -sf http://localhost:4173 | wc -c)" -ge 100 ] || exit 1'
          interval: 1s
          timeout: 3s
          retries: 5
          start_period: 600s

networks:
    bankless-backend-network:
        driver: bridge

volumes:
    cache:
        driver: local
    persist:
        driver: local
